require 'wypuot.options'
require 'wypuot.remap'
require 'wypuot.autocommands'

require 'wypuot.plugins.mason'
require 'wypuot.plugins.mini'
require 'wypuot.plugins.colors'
require 'wypuot.plugins.harpoon'
require 'wypuot.plugins.fugitive'
require 'wypuot.plugins.gitsigns'
require 'wypuot.plugins.treesitter'
require 'wypuot.plugins.undotree'
require 'wypuot.plugins.debug'
require 'wypuot.plugins.conform'
require 'wypuot.lsp'
